services:
  offlinekarte-search-db:
    image: postgis/postgis
    container_name: offlinekarte-search-db
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
  offlinekarte-search:
    build: .
    container_name: offlinekarte-search
    ports:
      - "8000:8000"
