services:
  offlinekarte-search-db:
    image: postgis/postgis:18-3.6
    container_name: offlinekarte-search-db
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    env_file: "search-db.env"
  offlinekarte-search:
    build: .
    container_name: offlinekarte-search
    ports:
      - "8000:8000"
    env_file: "search.env"
